name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ Login to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3️⃣ Build the Docker image
      - name: Build Docker Image
        run: docker build -t <dockerhub-username>/mini-project:latest .

      # 4️⃣ Push the image to DockerHub
      - name: Push Docker Image
        run: docker push <dockerhub-username>/mini-project:latest

      # 5️⃣ Copy deploy.sh to EC2
      - name: Copy deploy.sh to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "deploy.sh"
          target: "/home/ec2-user"

      # 6️⃣ Run deploy.sh on EC2
      - name: Run deploy.sh on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x /home/ec2-user/deploy.sh
            /home/ec2-user/deploy.sh
